### ISSUE TITLE
QR image to fit page width (CSS)

### ISSUE THREAD

**Issue by sjehuda** [ge0rg/easy-xmpp-invitation#36]
![image](https://user-images.githubusercontent.com/19249089/170865969-6728380c-2630-4ac1-9fc5-ccb587a55e10.png)

- QR image to fit page width
- QR code to be positioned at the middle of page

**Comment by ge0rg** [comment]
The QR code is meant for desktop clients, so that you can scan it with your mobile device from the desktop screen. There is no use in showing the QR code on a mobile screen, as you are the recipient of the invitation and not the sender.

**Comment by sjehuda** [comment]
This centers the image.
```diff
-    <div class="qrcode" id="qrcode"></div>
+    <div class="qrcode img-center" id="qrcode"></div>
```

What exactly the following code achieves?
```css
.qrcode {
	padding: 20px 5px 5px 5px;
	width: 42.5%;
	height: 100%;
	margin: auto;
}
```

I don't want to change the CSS code without asking.
